### PR TITLE
Updated SourceAPKs from APKMirror

### PR DESCRIPTION
**Pull request by NicholasBuse**
Updated SourceAPKs from APKMirror (2 commits, 1 to add new, 1 to remove old):
- Books v3.4.5
- Music v5.9.1854R.1904527
- Newsstand v3.4.0 (2015040712)
- Store v5.5.9
- YouTube v10.18.55

Misdiagnosed an issue with CalSync

Fixed extract_sources.sh typo that copy CalendarGooglePrebuilt to CalSync

### CODE REVIEW

**Comment by mfonville** [comment]
Thank you so much for your pull request :-)
Especially finding the typo, and saving me a lot of work on keeping the APKs update.
Btw, keep an eye on https://github.com/pagapps soon there will be a lot of new work committed for the next step in this project :-)

**Comment by NicholasBuse** [comment]
No problem, I'll keep on the new repo.

Also, I did not commit any of the changes to the repo created by running a build. The sizes.prop and and installer.data files had smaller sized across the board.  I have not looked into why yet, but I am building with cygwin on Win7x64. Maybe the zip I use compresses better? Or zipinfo reports differently?

**Comment by mfonville** [comment]
the sizes.prop and installer.data have to be generated by manually running the script.
So after updating the content of SourceAPKs, you should execute 'extract_soures.sh' and after that 'make_gprop.sh', 'make_installerdata.sh' and 'make_sizesprop.sh" and after that run 'make_package.sh'
This process will be changed and simplified soon though. You will see it appear in the new repository and XDA when I have the new scripts finished :-)

**Comment by NicholasBuse** [comment]
Sorry, I should have been more clear. I'm aware of the scripts and (mostly) their contents.  When running "make_sizesprop.sh" (even on your unchanged master) all of the sizes changed within sizes.prop (mostly the values were ~6kb less than their original values.)

I wouldn't worry about it, I just don't trust my setup enough to commit a build of the pa_gapps. I'll try to stay on top of APK updates in either repo.

**Comment by mfonville** [comment]
Ah, now I know what you mean. I think the difference might be result from the --apparent-size I use to get the size of the files. It can change per filesystem.

**Pull request merged**
