### PR TITLE
Keep 3.1.204.00

### PR DESCRIPTION
**Pull request by NicholasBuse**

### CODE REVIEW

**Comment by NicholasBuse** [comment]
Beat me again...

**Comment by mfonville** [comment]
lol.

Could you still have look btw at the android 5.0.x sources for in the new repo? That would really help me out :-)

**Comment by NicholasBuse** [comment]
Ok...I added the API-21 APKs to the pagapps/all repo.  I think we need to think through other differences:
1. /lib/libfacelock_jni.so and /lib/libjni_latinimegoogle.so differ between android versions
2. /framework/*.jar files also differ

This may be as simple as updating the folder structure and scrips to have a /21 and /22 subfolder...

**Comment by mfonville** [comment]
Thank you :-)
Considering these libs, we could maybe test if they are compatible with all versions, otherwise your solution is the most practical one. Was also thinking about writing a small script to automatically seize these libraries and apks from nexus images in the future.

Also for the longer term I still have to find out how 64bit android (and even x86 or x86_64) devices work considering their usage of libraries and apks.

**Pull request closed without merging**
